services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-sqlite-htmx
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
      - ./data:/workspace/data
    working_dir: /workspace
